version: '3.8'

services:

  organization-database:
    image: postgres:15
    environment:
      - POSTGRES_DB=organization_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - organization-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  department-database:
    image: postgres:15
    environment:
      - POSTGRES_DB=department_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - department-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  employee-database:
    image: postgres:15
    environment:
      - POSTGRES_DB=employee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - employee-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  organization-service:
    container_name: organization-service
    build:
      context: ./organization-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - organization-database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://organization-database:5432/organization_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      microservices-network:
    restart: on-failure

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      SERVER_PORT: 8761

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "9191:9191"
    networks:
      - microservices-network
    environment:
      SERVER_PORT: 9191

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    environment:
      SERVER_PORT: 8888

  employee-service:
    container_name: employee-service
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - employee-database
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_URL: jdbc:postgresql://employee-database:5432/employee_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      microservices-network:
    restart: on-failure


  depatment-service:
    container_name: depatment-service
    build:
      context: ./depatment-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - department-database
    networks:
      - microservices-network
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://department-database:5432/department_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root



volumes:
  organization-postgres-data:
  department-postgres-data:
  employee-postgres-data:

networks:
  microservices-network:
    driver: bridge
