version: '3.8'

services:

  organization-database:
    image: postgres:15
    environment:
      - POSTGRES_DB=organization_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - organization-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    ports:
       - "5433:5432"

  department-database:
    image: postgres:15
    environment:
      - POSTGRES_DB=department_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - department-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    ports:
      - "5434:5432"

  employee-database:
    image: postgres:15
    environment:
      - POSTGRES_DB=employee_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - employee-postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    ports:
      - "5435:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - microservices-network
    restart: always

  service-registry:
    build:
      context: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-network
    environment:
      SERVER_PORT: 8761

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "9191:9191"
    networks:
      - microservices-network
    environment:
      SERVER_PORT: 9191

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-network
    environment:
      SERVER_PORT: 8888

  depatment-service:
    container_name: depatment-service
    build:
      context: ./depatment-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - department-database
      - rabbitmq
    networks:
      - microservices-network
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://department-database:5432/department_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest

  organization-service:
    container_name: organization-service
    build:
      context: ./organization-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - organization-database
      - rabbitmq
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://organization-database:5432/organization_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      microservices-network:
    restart: on-failure

  employee-service:
    container_name: employee-service
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - employee-database
      - rabbitmq
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://employee-database:5432/employee_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=guest
      - SPRING_RABBITMQ_PASSWORD=guest
    networks:
      microservices-network:
    restart: on-failure

volumes:
  organization-postgres-data:
  department-postgres-data:
  employee-postgres-data:

networks:
  microservices-network:
    driver: bridge
